/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const AddLazyImport = createFileRoute('/add')()
const IndexLazyImport = createFileRoute('/')()
const EditMemberIdLazyImport = createFileRoute('/edit/$memberId')()

// Create/Update Routes

const AddLazyRoute = AddLazyImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/add.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const EditMemberIdLazyRoute = EditMemberIdLazyImport.update({
  id: '/edit/$memberId',
  path: '/edit/$memberId',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/edit.$memberId.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/add': {
      id: '/add'
      path: '/add'
      fullPath: '/add'
      preLoaderRoute: typeof AddLazyImport
      parentRoute: typeof rootRoute
    }
    '/edit/$memberId': {
      id: '/edit/$memberId'
      path: '/edit/$memberId'
      fullPath: '/edit/$memberId'
      preLoaderRoute: typeof EditMemberIdLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/add': typeof AddLazyRoute
  '/edit/$memberId': typeof EditMemberIdLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/add': typeof AddLazyRoute
  '/edit/$memberId': typeof EditMemberIdLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/add': typeof AddLazyRoute
  '/edit/$memberId': typeof EditMemberIdLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/add' | '/edit/$memberId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/add' | '/edit/$memberId'
  id: '__root__' | '/' | '/add' | '/edit/$memberId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  AddLazyRoute: typeof AddLazyRoute
  EditMemberIdLazyRoute: typeof EditMemberIdLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  AddLazyRoute: AddLazyRoute,
  EditMemberIdLazyRoute: EditMemberIdLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/add",
        "/edit/$memberId"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/add": {
      "filePath": "add.lazy.tsx"
    },
    "/edit/$memberId": {
      "filePath": "edit.$memberId.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
